default_stages: [commit, push]

fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [
          --allow-multiple-documents
        ]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        exclude: ^(tests/config.py|tests/build.py)
      - id: trailing-whitespace
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [--application-directories=app]
  - repo: local
    hooks:
      - id: check-poetry
        name: Poetry check
        description: Validates the structure of the pyproject.toml file
        language: python
        entry: poetry check
        pass_filenames: false
        files: pyproject.toml
        always_run: true
        additional_dependencies: [poetry]
      - id: black
        name: Black Lint
        types: [python]
        language: python
        entry: poetry run black
        types_or: [python, pyi]
      - id: flake8
        name: Flake 8 Lint
        language: python
        entry: poetry run flake8
        types_or: [python, pyi]
